namespace:

  name: sandbox

service:

  type: ClusterIP
  port: 4111
  targetPort: 3111
  protocol: TCP

image:

  repository: techtrends
  pullPolicy: IfNotPresent
  tag: "latest"

replicaCount: 1

resources:

  limits:

    cpu: 500m
    memory: 128Mi

  requests:

    cpu: 250m
    memory: 64Mi

containerPort: 3111

livenessProbe:

  path: /healthz
  port: 3111

readinessProbe:

  path: /healthz
  port: 3111
