# According to https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
# Secrets naming convention: https://docs.docker.com/ci-cd/github-actions/
# Also consulted: https://github.com/marketplace/actions/build-and-push-docker-images
name: TechTrends - Package with Docker

on:

  push:

    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:

          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:

          context: .
          file: ./Dockerfile
          push: true
          tags: okaxel/techtrends:latest
